// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwgnnfbtvndiaaprbuvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3Z25uZmJ0dm5kaWFhcHJidXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODA2MjksImV4cCI6MjA1OTc1NjYyOX0.F36UShWvwxPBZNPlw9qI9IjQ93ju_rRneSm64MgKGls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);